replicaCount: 1

image:
  # see https://hub.docker.com/repository/docker/baris1892/datascientest-movie-service/general
  repository: baris1892/datascientest-movie-service
  pullPolicy: Always

  # Overrides the image tag whose default is the chart appVersion.
  tag: "develop"

env:
  DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie-service-db/movie_db"

  # URL for the Movie Service to call the Cast Service internally within the Kubernetes cluster.
  # Use the Service name and its ClusterIP port (80), NOT the NodePort (30008).
  # Since both services run in the same namespace (e.g. dev), the host is simply "cast-service:80".
  CAST_SERVICE_HOST_URL: "http://cast-service:80/api/v1/casts/"

nameOverride: "movie-service"
fullnameOverride: "movie-service"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: NodePort
  port: 80
  nodePort: 30008
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

postgres:
  image: postgres:12.1-alpine
  pullPolicy: IfNotPresent
  username: movie_db_username
  password: movie_db_password
  db: movie_db
  storage: 1Gi
